- copy:
    src: vm_backup.sh
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755

- copy:
    src: vm_backup.lib
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0644

- copy:
    src: files/{{ inventory_hostname }}/vm_backup.cfg
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0644

- cron:
    name: "vm_backup"
    minute: 0
    hour: 3
    weekday: Friday
    job: /usr/local/bin/vm_backup.sh